USE codeup_test_db;
INSERT INTO albums ('artist', 'name', 'release_date', 'sales', 'genre')
VALUES ('Guns N Roses', 'Appetite for Destruction', '1987', '21.6', 'Hard Rock')
VALUES ('Santana', 'Supernatural', '1999', '20.5', 'Rock')
VALUES ('Pink Floyd', 'The Wall', '1979', '17.6', 'Progressive Rock')
VALUES ('Nirvana', 'Nevermind', '1991', '16.7', 'Grunge')
VALUES ('Metallica', 'Metallica', '1991', '21.2', 'Heavy Metal')
VALUES ('James Horner', 'Titanic: Music from the Motion Picture', '1997', '18.1', 'Soundtrack')
VALUES ('Dire Straits', 'Brothers in Arms', '1985', '17.7', 'Rock')
VALUES ('Bruce Springsteen', 'Born in the USA', '1984', '19.6', 'Rock')
VALUES ('The Beatles', 'Abbey Road', '1969', '14.4', 'Rock')
VALUES ('Madonna', 'The Immaculate Collection', '1990', '19.4', 'Pop')
VALUES ('The Beatles' '1', '2000', '22.6', 'Rock')
VALUES ('Celine Dion', 'Lets Talk About Love', '1997', '19.3', 'Pop')
VALUES ('Adele', '21', '2011', '25.3', 'Pop')
VALUES ('Various Artists', 'Dirty Dancing', '1987', '17.9', 'Pop, Rock, R&B')
VALUES ('Eagles', 'Hotel California', '1976', '21.5', 'Rock')
VALUES ('Michael Jackson', 'Dangerous', '1991', '19.4', 'Rock')
VALUES ('The Beatles', 'Sgt. Peppers Lonely Hearts Club Band', '1967', '13.1', 'Rock')
VALUES ('Celine Dion', 'Falling into You', '1996', '20.2', 'Pop')
VALUES ('Alanis Morissette', 'Jagged Little Pill', '1995', '24.4', 'Alternative Rock')
VALUES ('Michael Jackson', 'Bad', '1987', '23.6', 'Pop')
VALUES ('Led Zepplin', 'Led Zeppelin IV', '1971', '29.0', 'Heavy Metal')
VALUES ('Shania Twain', 'Come On Over', '1997', '29.6', 'Country, Pop')
VALUES ('Fleetwood Mac', 'Rumours', '1977', '27.9', 'Soft Rock')
VALUES ('Bee Gees', 'Saturday Night Fever', '1977', '20.6', 'Disco')
VALUES ('Eagles', 'Their Greatest Hits', '1976', '32.2', 'Rock, Soft Rock')
VALUES ('Meat Loaf', 'Bat Out of Hell', '1977', '27.4', 'Hark Rock')
VALUES ('Whitney Houston', 'The Bodyguard', '1992', '27.4', 'R&B, Soul, Pop, Soundtrack')
VALUES ('Pink Floyd', 'The Dark Side of the Moon', '1973', '24.2', 'Progressive Rock')
VALUES ('AC/DC', 'Back in Black', '1980', '26.1', 'Hard Rock')
VALUES ('Michael Jackson', 'Thriller', '1982', '47.3', 'Pop, Rock, R&B')